# Two Models will 1 will give adive 2 correct the advice 


from langchain_groq import ChatGroq
# import voyageai
from langchain.chat_models import init_chat_model
# from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace

from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.messages import HumanMessage , SystemMessage , AIMessage


load_dotenv()

database=[
    SystemMessage(content='You Just Give Opnion based on Your Instruction')

]

model1=init_chat_model(
    model ="mistral-medium-latest",
    model_provider="mistralai"
)

# model2=HuggingFaceEndpoint(
#     repo_id='meta-llama/Llama-3.1-8B-Instruct',
#     task='text-generation',
#     provider='auto'
# )


Main_model=ChatGroq(
    model='openai/gpt-oss-120b'
)



# Creating Template of promts

# Model One will Genrates the Text for You
prompt1 = ChatPromptTemplate.from_messages([
    (
        "system",
        """
You are an AI Advice Assistant.

Your job is to give practical, safe, and evidence-based advice based on the
user's situation.

Rules:
- Understand the user's problem before giving advice.
- Do not invent facts.
- Do not make extreme or dangerous recommendations.
- Clearly mention uncertainty when important.
- Give the most useful next step first.
- Keep the answer concise: maximum 4 lines.
"""
    ),
    (
        "user",
        """
User's situation:
{User}

Give the user the best practical advice and what they should do next.
Keep the response within 4 lines.
"""
    )
])


chain1= prompt1 | Main_model

user=input('Human : ')


model1_invoke=chain1.invoke({
    'User':user

})
print(("_"*10),"Model 1 Refined the Data",("_"*10))
print("")
print("model 1 : ",model1_invoke.content)



# Model 2 Will Refine first Model Mistakes
from langchain_core.prompts import ChatPromptTemplate

prompt2 = ChatPromptTemplate.from_messages([
    (
        "system",
        """
You are an AI Advice Reviewer and Critical Thinking Expert.

Your job is to review advice generated by another AI model.

Carefully check the advice for:
1. Factual mistakes
2. Incorrect assumptions
3. Missing important information
4. Unsafe or potentially harmful recommendations
5. Poor reasoning or weak logic
6. Whether the advice actually answers the user's problem

Do NOT reject advice just because it is different from your opinion.

If the advice is correct and safe, say that it is reasonable.

If it contains a mistake, clearly identify the mistake and provide a corrected
version.

Your goal is to improve the advice, not simply criticize it.

Return the result in exactly 3 parts:
Verdict: Good / Needs Improvement / Unsafe
Problem: Explain the main issue briefly
Improved Advice: Give the corrected advice briefly
"""
    ),
    (
        "user",
        """
Original User Situation:
{User}

Advice Generated by Model 1:
{model1_chat}

Review Model 1's advice carefully and determine whether it is correct,
reasonable, and safe.
"""
    )
])

chain2=prompt2 | Main_model

model2_invoke=chain2.invoke(
    {
        'model1_chat':model1_invoke    }
)
print("")
print(("_"*10),"Model 2 Refined the Data",("_"*10))
print("")
print("model 2 : ",model2_invoke.content)
